### ISSUE TITLE
lib/google-maps-device-locator/google-maps-device-locator.cpp:5:29: CellularHelper.h: No such file or directory

### ISSUE THREAD

**Issue by auriga-dev** [particle-iot/google-maps-device-locator#2]
When flashing the firmware I get this error: "lib/google-maps-device-locator/google-maps-device-locator.cpp:5:29: CellularHelper.h: No such file or directory"

I am trying to run it on an Electron 3G-U260

**Comment by benjaminhr** [comment]
Same @rickkas7

**Comment by rickkas7** [comment]
This typically happens when your Electron is not running system firmware 0.6.0 or later. Upgrading the system firmware should resolve the problem.

If it doesn't creating a new project may solve the problem.

**Comment by technobly** [comment]
I think I ran into this same issue... if you compile locally you won't have CellularHelper files present because they are included as a dependency https://github.com/particle-iot/google-maps-device-locator/blob/master/library.properties#L12

Run this to pull in the files:
```
google-maps-device-locator $ particle library add CellularHelper
```

**Comment by technobly** [comment]
FYI, CellularHelper latest version is 0.0.5, and this library depends on 0.0.4.  Not sure if 0.0.5 is compatible?

**Comment by technobly** [comment]
Looks like it should be compatible with a couple bug fixes between revisions.

The owner of this library should update the library.properties per above to 0.0.5, test and release :-)

**Comment by technobly** [comment]
![screen shot 2018-02-26 at 2 04 28 pm](https://user-images.githubusercontent.com/2249224/36692542-fda78e10-1afd-11e8-9f96-f5e26ff6cca5.png)

LOL, @rickkas7 do you have time to update this library?

**Comment by rickkas7** [comment]
Yes, I can test and update the CellularHelper to 0.0.5.
