### ISSUE TITLE
BORON LTE Compatible?

### ISSUE THREAD

**Issue by grady8081** [particle-iot/google-maps-device-locator#5]
Looking at the source, the library looks to be compatible with Boron LTE ( with the caveats of a single tower and a static operator, MCC, and MNC )

I have a Borton LTE with firmware 1.4, but can't get the deviceLocator event to fire off.  I was able to get it to work with my older photon with the same firmware version.  

Using version 0.05 and pretty much the stock example from https://docs.particle.io/tutorials/integrations/google-maps/.  ( I did update the example to use version 0.05 vice 0.04 )

Any tips/tricks?

**Comment by rickkas7** [comment]
It is not currently compatible with the Boron LTE. A future version will be compatible with newer versions of Device OS, probably 1.3.1 and later.

**Comment by grady8081** [comment]
> It is not currently compatible with the Boron LTE. A future version will be compatible with newer versions of Device OS, probably 1.3.1 and later.

Do you have a timeline in mind?  

Is it possible w/ v1.4.0 and simply not implemented in this lib?  If so,  I don't mind forking and  submitting back a PR if you want to point me in the right direction.   Just don't want to waste time if the lower level cellular libs aren't yet ready.

**Comment by grady8081** [comment]
@rickkas7 Am I on the right track that this call:
https://github.com/rickkas7/CellularHelper/blob/10486d1d81cdb5e728a77f5e397b5eb5631ce642/src/CellularHelper.cpp#L853

Should be "CEREG" vice "CREG" .  Per https://www.u-blox.com/sites/default/files/AT-CommandsExamples_AppNote_%28UBX-13001820%29.pdf ?

**Comment by rickkas7** [comment]
Version 0.0.5 of the google-maps-device-locator library now supports the Boron LTE and B Series B402 LTE SoM when using Device OS 1.2.1 or later! 

The library still works with older Device OS (back to 0.7.0) on other devices. 

For the E Series LTE and Electron LTE using 1.2.1 or later is recommended, otherwise the library won't work in Canada or Mexico properly unless you manually configure it. With 1.2.1 it works properly everywhere automatically.

**Comment by grady8081** [comment]
@rickkas7 Thank you! I was beating my head against the wall trying to figure out why "AT+CEREG?\r\n" was always just returning OK.

Assume that obtaining info for more than one tower is a limitation of the u-blox SARA R410 LTE modem?
